language: node_js
node_js:
- '10'
sudo: false
install:
- npm install --only=dev
- npm ci
before_script:
- node node_modules/eslint/bin/eslint.js .
script:
- node ./index.js help
after_script:
- npm test
deploy:
  provider: npm
  email: alex@edenup.com
  skip_cleanup: true
  api_key:
    secure: GhH9RqMOv/i5P+IJaaIOEVuuw+q01VsCgPvygo7Bkh2LjEhdlJF+0Z9kcvLHopIZsZVFjM1cIScElAhDyPwPEfoyzxB7Gxz9J7kLNd/aEp3j3+Eudj/6e1q/MJcUAfHDpXqCvr3BQJ3Xec4RCDQSdxQN4or3CKjQhXp3ZWY2Ge7+PgsH8S0znHD1Hd0Xrgeno0hkFAmwK8j5FjEwqwfaS1Gn5vKTXXEZxKUuXLaXm7FAbxj5r/OR4SenxnNQtexk9fPl6SC/rmVaievaobCgC1fZxaESdzgNokpHNyocXkD/M7tc7/CxziKYJt1LNCjNnsWubuTXCN/69eK7E3yfclZed827xkJfVpUoMs1njLncSEtL9tNhqkomKa/h6Mgb53t203pHCJ/WSnIuIUGlBiONiycmuG+Az3n8yN/eAxZ/GWbUdV9pq7BXcuK8vghvjbQb/d1aHiJcWWRO6WccryBAZjaWnG/jwu8A2ktoGF0I/XgHQixTkNS4UTLfHDtdeSHhA8++CvWI7fsv615QDm5tfFFvvGEfs9cRkn/HXnF2TlE7w0CwRQlPUdLN94Nn12nSvGjty5KuRAP3jg0h0vuijwqD3GPkCw4Rkod7rIKGrNc5LWfZgBbmEOPim6xBmey6cMBOx+860KUIu0QCLqocwDlBH+7dfPaeqyP/GcU=
  on:
    tags: true
    repo: eden-js/cli
    branch: master
